/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables;


import java.math.BigDecimal;
import java.util.Collection;

import org.example.mtgspotscrapper.model.databaseClasses.Scrapper;
import org.example.mtgspotscrapper.model.databaseClasses.tables.records.CardsimagesaddressesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cardsimagesaddresses extends TableImpl<CardsimagesaddressesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>scrapper.cardsimagesaddresses</code>
     */
    public static final Cardsimagesaddresses CARDSIMAGESADDRESSES = new Cardsimagesaddresses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardsimagesaddressesRecord> getRecordType() {
        return CardsimagesaddressesRecord.class;
    }

    /**
     * The column <code>scrapper.cardsimagesaddresses.multiverse_id</code>.
     */
    public final TableField<CardsimagesaddressesRecord, Integer> MULTIVERSE_ID = createField(DSL.name("multiverse_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>scrapper.cardsimagesaddresses.previous_price</code>.
     */
    public final TableField<CardsimagesaddressesRecord, BigDecimal> PREVIOUS_PRICE = createField(DSL.name("previous_price"), SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>scrapper.cardsimagesaddresses.actual_price</code>.
     */
    public final TableField<CardsimagesaddressesRecord, BigDecimal> ACTUAL_PRICE = createField(DSL.name("actual_price"), SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>scrapper.cardsimagesaddresses.image_url</code>.
     */
    public final TableField<CardsimagesaddressesRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>scrapper.cardsimagesaddresses.local_address</code>.
     */
    public final TableField<CardsimagesaddressesRecord, String> LOCAL_ADDRESS = createField(DSL.name("local_address"), SQLDataType.VARCHAR, this, "");

    private Cardsimagesaddresses(Name alias, Table<CardsimagesaddressesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cardsimagesaddresses(Name alias, Table<CardsimagesaddressesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "cardsimagesaddresses" as  SELECT downloadedcards.multiverse_id,
         downloadedcards.previous_price,
         downloadedcards.actual_price,
         downloadedcards.image_url,
         localaddresses.local_address
        FROM (downloadedcards
          LEFT JOIN localaddresses USING (multiverse_id));
        """), where);
    }

    /**
     * Create an aliased <code>scrapper.cardsimagesaddresses</code> table
     * reference
     */
    public Cardsimagesaddresses(String alias) {
        this(DSL.name(alias), CARDSIMAGESADDRESSES);
    }

    /**
     * Create an aliased <code>scrapper.cardsimagesaddresses</code> table
     * reference
     */
    public Cardsimagesaddresses(Name alias) {
        this(alias, CARDSIMAGESADDRESSES);
    }

    /**
     * Create a <code>scrapper.cardsimagesaddresses</code> table reference
     */
    public Cardsimagesaddresses() {
        this(DSL.name("cardsimagesaddresses"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Scrapper.SCRAPPER;
    }

    @Override
    public Cardsimagesaddresses as(String alias) {
        return new Cardsimagesaddresses(DSL.name(alias), this);
    }

    @Override
    public Cardsimagesaddresses as(Name alias) {
        return new Cardsimagesaddresses(alias, this);
    }

    @Override
    public Cardsimagesaddresses as(Table<?> alias) {
        return new Cardsimagesaddresses(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardsimagesaddresses rename(String name) {
        return new Cardsimagesaddresses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardsimagesaddresses rename(Name name) {
        return new Cardsimagesaddresses(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardsimagesaddresses rename(Table<?> name) {
        return new Cardsimagesaddresses(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardsimagesaddresses where(Condition condition) {
        return new Cardsimagesaddresses(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardsimagesaddresses where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardsimagesaddresses where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardsimagesaddresses where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardsimagesaddresses where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardsimagesaddresses where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardsimagesaddresses where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardsimagesaddresses where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardsimagesaddresses whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardsimagesaddresses whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
