/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables;


import java.math.BigDecimal;
import java.util.Collection;

import org.example.mtgspotscrapper.model.databaseClasses.Scrapper;
import org.example.mtgspotscrapper.model.databaseClasses.tables.records.CardswithpricesRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cardswithprices extends TableImpl<CardswithpricesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>scrapper.cardswithprices</code>
     */
    public static final Cardswithprices CARDSWITHPRICES = new Cardswithprices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CardswithpricesRecord> getRecordType() {
        return CardswithpricesRecord.class;
    }

    /**
     * The column <code>scrapper.cardswithprices.multiverse_id</code>.
     */
    public final TableField<CardswithpricesRecord, Integer> MULTIVERSE_ID = createField(DSL.name("multiverse_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>scrapper.cardswithprices.previous_price</code>.
     */
    public final TableField<CardswithpricesRecord, BigDecimal> PREVIOUS_PRICE = createField(DSL.name("previous_price"), SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>scrapper.cardswithprices.actual_price</code>.
     */
    public final TableField<CardswithpricesRecord, BigDecimal> ACTUAL_PRICE = createField(DSL.name("actual_price"), SQLDataType.NUMERIC(4, 2), this, "");

    private Cardswithprices(Name alias, Table<CardswithpricesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cardswithprices(Name alias, Table<CardswithpricesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "cardswithprices" as  SELECT downloadedcards.multiverse_id,
         downloadedcards.previous_price,
         downloadedcards.actual_price
        FROM downloadedcards;
        """), where);
    }

    /**
     * Create an aliased <code>scrapper.cardswithprices</code> table reference
     */
    public Cardswithprices(String alias) {
        this(DSL.name(alias), CARDSWITHPRICES);
    }

    /**
     * Create an aliased <code>scrapper.cardswithprices</code> table reference
     */
    public Cardswithprices(Name alias) {
        this(alias, CARDSWITHPRICES);
    }

    /**
     * Create a <code>scrapper.cardswithprices</code> table reference
     */
    public Cardswithprices() {
        this(DSL.name("cardswithprices"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Scrapper.SCRAPPER;
    }

    @Override
    public Cardswithprices as(String alias) {
        return new Cardswithprices(DSL.name(alias), this);
    }

    @Override
    public Cardswithprices as(Name alias) {
        return new Cardswithprices(alias, this);
    }

    @Override
    public Cardswithprices as(Table<?> alias) {
        return new Cardswithprices(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardswithprices rename(String name) {
        return new Cardswithprices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardswithprices rename(Name name) {
        return new Cardswithprices(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cardswithprices rename(Table<?> name) {
        return new Cardswithprices(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardswithprices where(Condition condition) {
        return new Cardswithprices(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardswithprices where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardswithprices where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardswithprices where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardswithprices where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardswithprices where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardswithprices where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cardswithprices where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardswithprices whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cardswithprices whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
