/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables;


import java.math.BigDecimal;
import java.util.Collection;

import org.example.mtgspotscrapper.model.databaseClasses.Scrapper;
import org.example.mtgspotscrapper.model.databaseClasses.tables.records.FulldownloadedcarddataRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Fulldownloadedcarddata extends TableImpl<FulldownloadedcarddataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>scrapper.fulldownloadedcarddata</code>
     */
    public static final Fulldownloadedcarddata FULLDOWNLOADEDCARDDATA = new Fulldownloadedcarddata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FulldownloadedcarddataRecord> getRecordType() {
        return FulldownloadedcarddataRecord.class;
    }

    /**
     * The column <code>scrapper.fulldownloadedcarddata.multiverse_id</code>.
     */
    public final TableField<FulldownloadedcarddataRecord, Integer> MULTIVERSE_ID = createField(DSL.name("multiverse_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>scrapper.fulldownloadedcarddata.previous_price</code>.
     */
    public final TableField<FulldownloadedcarddataRecord, BigDecimal> PREVIOUS_PRICE = createField(DSL.name("previous_price"), SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>scrapper.fulldownloadedcarddata.actual_price</code>.
     */
    public final TableField<FulldownloadedcarddataRecord, BigDecimal> ACTUAL_PRICE = createField(DSL.name("actual_price"), SQLDataType.NUMERIC(4, 2), this, "");

    /**
     * The column <code>scrapper.fulldownloadedcarddata.image_url</code>.
     */
    public final TableField<FulldownloadedcarddataRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>scrapper.fulldownloadedcarddata.card_name</code>.
     */
    public final TableField<FulldownloadedcarddataRecord, String> CARD_NAME = createField(DSL.name("card_name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>scrapper.fulldownloadedcarddata.local_address</code>.
     */
    public final TableField<FulldownloadedcarddataRecord, String> LOCAL_ADDRESS = createField(DSL.name("local_address"), SQLDataType.VARCHAR, this, "");

    private Fulldownloadedcarddata(Name alias, Table<FulldownloadedcarddataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Fulldownloadedcarddata(Name alias, Table<FulldownloadedcarddataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "fulldownloadedcarddata" as  SELECT downloadedcards.multiverse_id,
         downloadedcards.previous_price,
         downloadedcards.actual_price,
         downloadedcards.image_url,
         allcards.card_name,
         localaddresses.local_address
        FROM ((downloadedcards
          LEFT JOIN allcards USING (multiverse_id))
          LEFT JOIN localaddresses USING (multiverse_id));
        """), where);
    }

    /**
     * Create an aliased <code>scrapper.fulldownloadedcarddata</code> table
     * reference
     */
    public Fulldownloadedcarddata(String alias) {
        this(DSL.name(alias), FULLDOWNLOADEDCARDDATA);
    }

    /**
     * Create an aliased <code>scrapper.fulldownloadedcarddata</code> table
     * reference
     */
    public Fulldownloadedcarddata(Name alias) {
        this(alias, FULLDOWNLOADEDCARDDATA);
    }

    /**
     * Create a <code>scrapper.fulldownloadedcarddata</code> table reference
     */
    public Fulldownloadedcarddata() {
        this(DSL.name("fulldownloadedcarddata"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Scrapper.SCRAPPER;
    }

    @Override
    public Fulldownloadedcarddata as(String alias) {
        return new Fulldownloadedcarddata(DSL.name(alias), this);
    }

    @Override
    public Fulldownloadedcarddata as(Name alias) {
        return new Fulldownloadedcarddata(alias, this);
    }

    @Override
    public Fulldownloadedcarddata as(Table<?> alias) {
        return new Fulldownloadedcarddata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fulldownloadedcarddata rename(String name) {
        return new Fulldownloadedcarddata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fulldownloadedcarddata rename(Name name) {
        return new Fulldownloadedcarddata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fulldownloadedcarddata rename(Table<?> name) {
        return new Fulldownloadedcarddata(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fulldownloadedcarddata where(Condition condition) {
        return new Fulldownloadedcarddata(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fulldownloadedcarddata where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fulldownloadedcarddata where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fulldownloadedcarddata where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fulldownloadedcarddata where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fulldownloadedcarddata where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fulldownloadedcarddata where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Fulldownloadedcarddata where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fulldownloadedcarddata whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Fulldownloadedcarddata whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
