/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables;


import java.util.Collection;

import org.example.mtgspotscrapper.model.databaseClasses.Scrapper;
import org.example.mtgspotscrapper.model.databaseClasses.tables.records.ListswithlogosRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Listswithlogos extends TableImpl<ListswithlogosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>scrapper.listswithlogos</code>
     */
    public static final Listswithlogos LISTSWITHLOGOS = new Listswithlogos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ListswithlogosRecord> getRecordType() {
        return ListswithlogosRecord.class;
    }

    /**
     * The column <code>scrapper.listswithlogos.logo_id</code>.
     */
    public final TableField<ListswithlogosRecord, Integer> LOGO_ID = createField(DSL.name("logo_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>scrapper.listswithlogos.list_id</code>.
     */
    public final TableField<ListswithlogosRecord, Integer> LIST_ID = createField(DSL.name("list_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>scrapper.listswithlogos.list_name</code>.
     */
    public final TableField<ListswithlogosRecord, String> LIST_NAME = createField(DSL.name("list_name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>scrapper.listswithlogos.logo_path</code>.
     */
    public final TableField<ListswithlogosRecord, String> LOGO_PATH = createField(DSL.name("logo_path"), SQLDataType.VARCHAR, this, "");

    private Listswithlogos(Name alias, Table<ListswithlogosRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Listswithlogos(Name alias, Table<ListswithlogosRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "listswithlogos" as  SELECT lists.logo_id,
         lists.list_id,
         lists.list_name,
         listslogos.logo_path
        FROM (lists
          LEFT JOIN listslogos USING (logo_id));
        """), where);
    }

    /**
     * Create an aliased <code>scrapper.listswithlogos</code> table reference
     */
    public Listswithlogos(String alias) {
        this(DSL.name(alias), LISTSWITHLOGOS);
    }

    /**
     * Create an aliased <code>scrapper.listswithlogos</code> table reference
     */
    public Listswithlogos(Name alias) {
        this(alias, LISTSWITHLOGOS);
    }

    /**
     * Create a <code>scrapper.listswithlogos</code> table reference
     */
    public Listswithlogos() {
        this(DSL.name("listswithlogos"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Scrapper.SCRAPPER;
    }

    @Override
    public Listswithlogos as(String alias) {
        return new Listswithlogos(DSL.name(alias), this);
    }

    @Override
    public Listswithlogos as(Name alias) {
        return new Listswithlogos(alias, this);
    }

    @Override
    public Listswithlogos as(Table<?> alias) {
        return new Listswithlogos(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Listswithlogos rename(String name) {
        return new Listswithlogos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Listswithlogos rename(Name name) {
        return new Listswithlogos(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Listswithlogos rename(Table<?> name) {
        return new Listswithlogos(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Listswithlogos where(Condition condition) {
        return new Listswithlogos(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Listswithlogos where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Listswithlogos where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Listswithlogos where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Listswithlogos where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Listswithlogos where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Listswithlogos where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Listswithlogos where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Listswithlogos whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Listswithlogos whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
