/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses;


import org.example.mtgspotscrapper.model.databaseClasses.tables.Allcardsview;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Cardsimagesaddresses;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Cardswithprices;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Fulldownloadedcarddata;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Fulllistdata;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Listswithlogos;


/**
 * Convenience access to all tables in scrapper.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>scrapper.allcardsview</code>.
     */
    public static final Allcardsview ALLCARDSVIEW = Allcardsview.ALLCARDSVIEW;

    /**
     * The table <code>scrapper.cardsimagesaddresses</code>.
     */
    public static final Cardsimagesaddresses CARDSIMAGESADDRESSES = Cardsimagesaddresses.CARDSIMAGESADDRESSES;

    /**
     * The table <code>scrapper.cardswithprices</code>.
     */
    public static final Cardswithprices CARDSWITHPRICES = Cardswithprices.CARDSWITHPRICES;

    /**
     * The table <code>scrapper.fulldownloadedcarddata</code>.
     */
    public static final Fulldownloadedcarddata FULLDOWNLOADEDCARDDATA = Fulldownloadedcarddata.FULLDOWNLOADEDCARDDATA;

    /**
     * The table <code>scrapper.fulllistdata</code>.
     */
    public static final Fulllistdata FULLLISTDATA = Fulllistdata.FULLLISTDATA;

    /**
     * The table <code>scrapper.listswithlogos</code>.
     */
    public static final Listswithlogos LISTSWITHLOGOS = Listswithlogos.LISTSWITHLOGOS;
}
