/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses;


import org.example.mtgspotscrapper.model.databaseClasses.tables.Cards;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Fullcarddata;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Fulllistdata;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Listcards;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Lists;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Listslogos;
import org.example.mtgspotscrapper.model.databaseClasses.tables.Localaddresses;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.cards</code>.
     */
    public static final Cards CARDS = Cards.CARDS;

    /**
     * The table <code>public.fullcarddata</code>.
     */
    public static final Fullcarddata FULLCARDDATA = Fullcarddata.FULLCARDDATA;

    /**
     * The table <code>public.fulllistdata</code>.
     */
    public static final Fulllistdata FULLLISTDATA = Fulllistdata.FULLLISTDATA;

    /**
     * The table <code>public.listcards</code>.
     */
    public static final Listcards LISTCARDS = Listcards.LISTCARDS;

    /**
     * The table <code>public.lists</code>.
     */
    public static final Lists LISTS = Lists.LISTS;

    /**
     * The table <code>public.listslogos</code>.
     */
    public static final Listslogos LISTSLOGOS = Listslogos.LISTSLOGOS;

    /**
     * The table <code>public.localaddresses</code>.
     */
    public static final Localaddresses LOCALADDRESSES = Localaddresses.LOCALADDRESSES;
}
