-- DROP TABLE IF EXISTS ListCards CASCADE ;
-- DROP TABLE IF EXISTS ListsLogos CASCADE ;
-- DROP TABLE IF EXISTS Lists CASCADE ;
-- DROP TABLE IF EXISTS DownloadedCards CASCADE ;
-- DROP TABLE IF EXISTS LocalAddresses CASCADE ;
-- DROP TABLE IF EXISTS NamesAndMultiverseid CASCADE ;
-- DROP TABLE IF EXISTS allcards CASCADE ;
--
-- DROP VIEW IF EXISTS FullDownloadedCardData CASCADE ;
-- DROP VIEW IF EXISTS FullListData CASCADE ;

DROP SCHEMA IF EXISTS scrapper CASCADE ;