DROP TABLE IF EXISTS ListCards CASCADE ;
DROP TABLE IF EXISTS ListsLogos CASCADE ;
DROP TABLE IF EXISTS Lists CASCADE ;
DROP TABLE IF EXISTS Cards CASCADE ;
DROP TABLE IF EXISTS LocalAddresses CASCADE ;
DROP VIEW IF EXISTS FullCardData CASCADE ;
