/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables.records;


import org.example.mtgspotscrapper.model.databaseClasses.tables.Allcardsview;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AllcardsviewRecord extends TableRecordImpl<AllcardsviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>scrapper.allcardsview.multiverse_id</code>.
     */
    public void setMultiverseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>scrapper.allcardsview.multiverse_id</code>.
     */
    public Integer getMultiverseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>scrapper.allcardsview.card_name</code>.
     */
    public void setCardName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>scrapper.allcardsview.card_name</code>.
     */
    public String getCardName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllcardsviewRecord
     */
    public AllcardsviewRecord() {
        super(Allcardsview.ALLCARDSVIEW);
    }

    /**
     * Create a detached, initialised AllcardsviewRecord
     */
    public AllcardsviewRecord(Integer multiverseId, String cardName) {
        super(Allcardsview.ALLCARDSVIEW);

        setMultiverseId(multiverseId);
        setCardName(cardName);
        resetChangedOnNotNull();
    }
}
