/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables.records;


import java.math.BigDecimal;

import org.example.mtgspotscrapper.model.databaseClasses.tables.Fulldownloadedcarddata;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FulldownloadedcarddataRecord extends TableRecordImpl<FulldownloadedcarddataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>scrapper.fulldownloadedcarddata.multiverse_id</code>.
     */
    public void setMultiverseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>scrapper.fulldownloadedcarddata.multiverse_id</code>.
     */
    public Integer getMultiverseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>scrapper.fulldownloadedcarddata.previous_price</code>.
     */
    public void setPreviousPrice(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>scrapper.fulldownloadedcarddata.previous_price</code>.
     */
    public BigDecimal getPreviousPrice() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>scrapper.fulldownloadedcarddata.actual_price</code>.
     */
    public void setActualPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>scrapper.fulldownloadedcarddata.actual_price</code>.
     */
    public BigDecimal getActualPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>scrapper.fulldownloadedcarddata.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>scrapper.fulldownloadedcarddata.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>scrapper.fulldownloadedcarddata.card_name</code>.
     */
    public void setCardName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>scrapper.fulldownloadedcarddata.card_name</code>.
     */
    public String getCardName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>scrapper.fulldownloadedcarddata.local_address</code>.
     */
    public void setLocalAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>scrapper.fulldownloadedcarddata.local_address</code>.
     */
    public String getLocalAddress() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FulldownloadedcarddataRecord
     */
    public FulldownloadedcarddataRecord() {
        super(Fulldownloadedcarddata.FULLDOWNLOADEDCARDDATA);
    }

    /**
     * Create a detached, initialised FulldownloadedcarddataRecord
     */
    public FulldownloadedcarddataRecord(Integer multiverseId, BigDecimal previousPrice, BigDecimal actualPrice, String imageUrl, String cardName, String localAddress) {
        super(Fulldownloadedcarddata.FULLDOWNLOADEDCARDDATA);

        setMultiverseId(multiverseId);
        setPreviousPrice(previousPrice);
        setActualPrice(actualPrice);
        setImageUrl(imageUrl);
        setCardName(cardName);
        setLocalAddress(localAddress);
        resetChangedOnNotNull();
    }
}
