/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables.records;


import java.math.BigDecimal;

import org.example.mtgspotscrapper.model.databaseClasses.tables.Fullcarddata;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FullcarddataRecord extends TableRecordImpl<FullcarddataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fullcarddata.multiverse_id</code>.
     */
    public void setMultiverseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fullcarddata.multiverse_id</code>.
     */
    public Integer getMultiverseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.fullcarddata.card_name</code>.
     */
    public void setCardName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fullcarddata.card_name</code>.
     */
    public String getCardName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.fullcarddata.previous_price</code>.
     */
    public void setPreviousPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fullcarddata.previous_price</code>.
     */
    public BigDecimal getPreviousPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.fullcarddata.actual_price</code>.
     */
    public void setActualPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fullcarddata.actual_price</code>.
     */
    public BigDecimal getActualPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.fullcarddata.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fullcarddata.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.fullcarddata.local_address</code>.
     */
    public void setLocalAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fullcarddata.local_address</code>.
     */
    public String getLocalAddress() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FullcarddataRecord
     */
    public FullcarddataRecord() {
        super(Fullcarddata.FULLCARDDATA);
    }

    /**
     * Create a detached, initialised FullcarddataRecord
     */
    public FullcarddataRecord(Integer multiverseId, String cardName, BigDecimal previousPrice, BigDecimal actualPrice, String imageUrl, String localAddress) {
        super(Fullcarddata.FULLCARDDATA);

        setMultiverseId(multiverseId);
        setCardName(cardName);
        setPreviousPrice(previousPrice);
        setActualPrice(actualPrice);
        setImageUrl(imageUrl);
        setLocalAddress(localAddress);
        resetChangedOnNotNull();
    }
}
