/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables.records;


import org.example.mtgspotscrapper.model.databaseClasses.tables.Listcards;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ListcardsRecord extends TableRecordImpl<ListcardsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.listcards.list_id</code>.
     */
    public void setListId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.listcards.list_id</code>.
     */
    public Integer getListId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.listcards.multiverse_id</code>.
     */
    public void setMultiverseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.listcards.multiverse_id</code>.
     */
    public Integer getMultiverseId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListcardsRecord
     */
    public ListcardsRecord() {
        super(Listcards.LISTCARDS);
    }

    /**
     * Create a detached, initialised ListcardsRecord
     */
    public ListcardsRecord(Integer listId, Integer multiverseId) {
        super(Listcards.LISTCARDS);

        setListId(listId);
        setMultiverseId(multiverseId);
        resetChangedOnNotNull();
    }
}
