/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables.records;


import org.example.mtgspotscrapper.model.databaseClasses.tables.Listslogos;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ListslogosRecord extends UpdatableRecordImpl<ListslogosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.listslogos.logo_id</code>.
     */
    public void setLogoId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.listslogos.logo_id</code>.
     */
    public Integer getLogoId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.listslogos.logo_path</code>.
     */
    public void setLogoPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.listslogos.logo_path</code>.
     */
    public String getLogoPath() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListslogosRecord
     */
    public ListslogosRecord() {
        super(Listslogos.LISTSLOGOS);
    }

    /**
     * Create a detached, initialised ListslogosRecord
     */
    public ListslogosRecord(Integer logoId, String logoPath) {
        super(Listslogos.LISTSLOGOS);

        setLogoId(logoId);
        setLogoPath(logoPath);
        resetChangedOnNotNull();
    }
}
