/*
 * This file is generated by jOOQ.
 */
package org.example.mtgspotscrapper.model.databaseClasses.tables.records;


import org.example.mtgspotscrapper.model.databaseClasses.tables.Localaddresses;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LocaladdressesRecord extends UpdatableRecordImpl<LocaladdressesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.localaddresses.multiverse_id</code>.
     */
    public void setMultiverseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.localaddresses.multiverse_id</code>.
     */
    public Integer getMultiverseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.localaddresses.local_address</code>.
     */
    public void setLocalAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.localaddresses.local_address</code>.
     */
    public String getLocalAddress() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocaladdressesRecord
     */
    public LocaladdressesRecord() {
        super(Localaddresses.LOCALADDRESSES);
    }

    /**
     * Create a detached, initialised LocaladdressesRecord
     */
    public LocaladdressesRecord(Integer multiverseId, String localAddress) {
        super(Localaddresses.LOCALADDRESSES);

        setMultiverseId(multiverseId);
        setLocalAddress(localAddress);
        resetChangedOnNotNull();
    }
}
